# Generated by Django 5.2.7 on 2025-10-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='lesson',
        ),
        migrations.AddField(
            model_name='grade',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.homework'),
        ),
    ]
