# Generated by Django 5.2.7 on 2025-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_homework_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
