# Generated by Django 5.2.7 on 2025-11-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_homeworksubmission_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='title',
            new_name='name',
        ),
    ]
