# Generated by Django 5.2.7 on 2025-11-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_title_homework_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='submission',
        ),
        migrations.AddField(
            model_name='grade',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='common.homework'),
        ),
    ]
